# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-31 10:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=30, verbose_name='团队名')),
                ('teamdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_pass', models.CharField(max_length=10, verbose_name='是否通过验证')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '团队审核中间表',
                'verbose_name_plural': '团队审核中间表',
            },
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': '团队', 'verbose_name_plural': '团队'},
        ),
        migrations.RemoveField(
            model_name='team',
            name='is_pass',
        ),
    ]
