# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-14 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
