# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-14 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171114_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamer_temp',
            name='photo',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
    ]
