# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-08 14:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20171122_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rulestrs', models.CharField(max_length=2000, verbose_name='规则')),
                ('score', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': '规则得分',
                'verbose_name_plural': '规则得分',
            },
        ),
        migrations.CreateModel(
            name='Rule_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myscore', models.FloatField(default=0.0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Rule_score', verbose_name='规则')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户规则评分',
                'verbose_name_plural': '用户规则评分',
            },
        ),
    ]
