# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-16 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_analysis_manage'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis_manage',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='是否显示'),
        ),
    ]
